apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/Luis20matias/Data_engineer_projects.git'
    path: modern-data-stack-k8s-master/infra/src/helm-charts/airflow
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: 'modern-data-plataform-cluster'
    namespace: orchestrator
    server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
