apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trino-ingress
spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: trino-cluster
                port:
                  number: 8080
