apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hive-metastore
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/owshq-academy/master-spark-programming.git'
    path: infra/helm-charts/hive-metastore
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: 'do-nyc1-orn-polaris-dev'
    namespace: metastore
    server: ''
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
